export interface IMethodAnalysis {
  IdMethodAnalysis: number
  Codigo : string;
  Operacion : string;
  Rate: number;
  JornadaLaboral: number;
  IdManufacturing : number;
  Manufacturing : string;
  IdProducto : number;
  Producto : string;
  IdFamily : number;
  Family : string;
  IdSecuence : number;
  Secuence : number;
  IdDataMachine : number;
  DataMachine : string;
  Delay :  number;
  Personal : number;
  Fatigue : number;
  IdStitchType : number;
  TypeStitch : string;
  IdNeedle : number;
  NeedleType : string;
  IdRpm : number;
  Rpm: number;
  IdStitchInch : number;
  StitchInch : number;
  IdTela: number;
  Tela: string;
  IdOunce : number;
  Ounce: number;
  IdCaliber : number;
  Caliber : string;
  IdFeedDog : number
  FeedDog : string;
  IdPresserFoot : number;
  PresserFoot : string;
  IdFolder : number;
  Folder : string;
  MateriaPrima_1: string;
  MateriaPrima_2 : string;
  MateriaPrima_3 : string;
  FechaRegistro : Date;
  IdUsuario : number;
  Usuario : string;
  FactorSewing : number;
  FactorSewingAccuracy : number;
  Sewing : number;
  Tmus_Mac : number;
  Tmus_MinL : number;
  Min_Mac : number;
  Min_NML : number;
  Min_Mac_CC : number;
  Min_NML_CC : number;
  Sam : number;
  ProducJL : number;
  Precio : number;
  IdUsuarioModifica : number;
  UsuarioModifica : string;
  FechaModifica : Date;
  }
